@startuml

title __REPO's Class Diagram__\n

  namespace vera {
    namespace repo {
      interface vera.repo.AdminRepo {
          {abstract} + findByMailA()
      }
    }
  }
  

  namespace vera {
    namespace repo {
      interface vera.repo.DeviceRepo {
          {abstract} + findAll()
          {abstract} + findBySerialNumber()
          {abstract} + findDevicesByUserIdOrderByIdD()
      }
    }
  }
  

  namespace vera {
    namespace repo {
      interface vera.repo.IndicationRepo {
      }
    }
  }
  

  namespace vera {
    namespace repo {
      interface vera.repo.PaidUpTariffsRepo {
      }
    }
  }
  

  namespace vera {
    namespace repo {
      interface vera.repo.RequestRepo {
      }
    }
  }
  

  namespace vera {
    namespace repo {
      interface vera.repo.ServiceRepo {
          {abstract} + findAllByOrderByDateS()
          {abstract} + findByWorkerIdW()
      }
    }
  }
  

  namespace vera {
    namespace repo {
      interface vera.repo.TariffRepo {
      }
    }
  }
  

  namespace vera {
    namespace repo {
      interface vera.repo.UserAuthoritiesRepo {
          {abstract} + findUserAuthoritiesByAuthority()
      }
    }
  }
  

  namespace vera {
    namespace repo {
      interface vera.repo.UserRepo {
          {abstract} + findAllById()
          {abstract} + findByMailU()
          {abstract} + findByUsername()
      }
    }
  }
  

  namespace vera {
    namespace repo {
      interface vera.repo.WorkerRepo {
          {abstract} + findAllByOrderByInfoW()
          {abstract} + findByMailW()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
